export const authConstant = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_CHECK_ID: "USER_CHECK_ID",
  SET_PROFILE_PHOTO: "SET_PROFILE_PHOTO",
  CHAT_INIT: "CHAT_INIT",
};

export const userconstant = {
  ADD_FRIEND: "ADD_FRIEND",
  GET_REALTIME_USERS: "GET_REALTIME_USERS",
  GET_FRIENDS: "GET_FRIENDS",
  GET_REALTIME_MESSAGES: "GET_REALTIME_MESSAGES",
  GET_UNSEEN: "GET_UNSEEN",
};
